title: "cartographie-acteurs-design"
files_origin: ./fiches/
export_target: ./public
select_origin: "directory"
nodes_origin: ""
links_origin: ""
nodes_online: ""
links_online: ""
images_origin: ""
history: true
focus_max: 2
record_types:
  undefined:
    fill: "#858585"
    stroke: "#858585"
  association:
    fill: "#858585"
    stroke: "#858585"
link_types:
  undefined:
    stroke: "simple"
    color: "#e1e1e1"
